# Step 1: Use a node image for building the React app
FROM node:18-alpine as build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and yarn.lock (or package-lock.json if you're using npm)
COPY package.json package-lock.json ./

# Install dependencies using npm
RUN npm install --legacy-peer-deps

# Copy the rest of the application
COPY . .

# Build the React app for production
RUN npm run build


# Step 2: Use an Nginx image to serve the build files
FROM nginx:alpine

# Copy the build output to the Nginx container
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 for the web server
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
