# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory (we're using npm)
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --legacy-peer-deps


# Copy the rest of the application files
COPY . .

# Expose the app's port
EXPOSE 5001

# Command to run the app
CMD ["npm", "start"]
